DEMO = {
    "NLOG":{
        "port":"5158",
        "ip":"192.168.8.25"
    },
    "MONGO":{
        "password":"8EBDB935F8B30DA2",
        "port":"27017",
        "host":"192.168.8.28",
        "user":"ccinfoadm"
    },
    "REDIS":{
        "password":"111111",
        "port":"6379",
        "host":"192.168.8.30",
        "db":"1"
    },
    "API":{
        "TIDY_SERVER_API":"http://10.0.5.43:8080",
        "INTSIG_API":"https://api-sandbox.intsig.net",
        "COMPANY_HOLDER_API":"http://10.0.3.185:5945",
        "FILE_API":"http://crawler-fs.intsig.net/camfs",
        "NEW_FILE_API":"http://crawler-fs.intsig.net",
        "YUNYING_PUSH_API":"http://ccpush-sandbox.intsig.net",
        "COMPANY_FILE_API":"http://ss-sandbox.intsig.net/yemai/qiye/vip",
        "COMPANY_INFO_API":"http://ss-sandbox.intsig.net/yemai/vip",
        "CORP_QUERY_API":"http://srh-sandbox.intsig.net",
        "COMPANY_INCREMENT_API":"http://10.0.3.185:5976/company_increment"
    },
    "JOB":{
        "ITORANGE":{
            "DO_MR2P":"1",
            "TRANS_MAP":"MAP_ITORANGE",
            "MONGO_COLLECTION":"itorange",
            "MR2P_PROCESSOR":"company2data.Company2data",
            "PULL_STRATEGY":"mongo",
            "PUSH_REDIS_KEY":"com.qxb.qxspider.push_itorange",
            "MONGO_DB":"d_ccinfo"
        }
    },

	"DATA_MAP":{
	    "trans_company_increment_map":{
	        "rival_companies":[
	            None,
	            "my_default_func"
	        ],
	        "logo_url":[
	            "new['logo_url']",
	            "my_eval_func"
	        ],
	        "modify_time":[
	            "new['last_update']",
	            "my_eval_func"
	        ],
	        "description":[
	            "new['description']",
	            "my_eval_func"
	        ],
	        "scale":[
	            "new['scale']",
	            "my_eval_func"
	        ],
	        "source":[
	            "itorange",
	            "my_default_func"
	        ],
	        "logo_cname":[
	            None,
	            "my_default_func"
	        ],
	        "english_name":[
	            None,
	            "my_default_func"
	        ],
	        "products":[
	            "[new['simple_name']]",
	            "my_eval_func"
	        ],
	        "revenue":[
	            "new['revenue']",
	            "my_eval_func"
	        ],
	        "investment_state":[
	            None,
	            "my_default_func"
	        ],
	        "simple_name":[
	            "new['simple_name']",
	            "my_eval_func"
	        ],
	        "product_list":[
	            None,
	            "my_default_func"
	        ],
	        "email":[
	            "[new['email']]",
	            "my_eval_func"
	        ],
	        "cover_url":[
	            None,
	            "my_default_func"
	        ],
	        "address":[
	            "new['address']",
	            "my_eval_func"
	        ],
	        "business":[
	            "new['key_words']",
	            "my_eval_func"
	        ],
	        "client_time":[
	            "",
	            "my_time_func"
	        ],
	        "company_id":[
	            "new['company_id']",
	            "my_eval_func"
	        ],
	        "create_time":[
	            "new['founding_time']",
	            "my_eval_func"
	        ],
	        "company_web":[
	            "[new['company_web']]",
	            "my_eval_func"
	        ],
	        "company_faxed":[
	            None,
	            "my_default_func"
	        ],
	        "opponents":[
	            "new['rival_companies']",
	            "my_eval_func"
	        ],
	        "postcode":[
	            None,
	            "my_default_func"
	        ],
	        "key_words":[
	            "new['key_words']",
	            "my_eval_func"
	        ],
	        "company_phones":[
	            "[new['company_phones']]",
	            "my_eval_func"
	        ],
	        "client_list":[
	            None,
	            "my_default_func"
	        ],
	        "upload_time":[
	            "new['last_update']",
	            "my_eval_func"
	        ],
	        "user_id":[
	            None,
	            "my_default_func"
	        ],
	        "company_name":[
	            "new['company_name']",
	            "my_eval_func"
	        ],
	        "industries":[
	            None,
	            "my_default_func"
	        ],
	        "style":[
	            "1",
	            "my_default_func"
	        ],
	        "contacts":[
	            None,
	            "my_default_func"
	        ]
	    },
	    "trans_product_map":{
	        "op":[
	            "add",
	            "my_default_func"
	        ],
	        "client_time":[
	            "",
	            "my_milltime_func"
	        ],
	        "multi_content":[
	            "new['multi_content']",
	            "my_eval_func"
	        ],
	        "key_words":[
	            "new['key_words']",
	            "my_eval_func"
	        ],
	        "source":[
	            "11",
	            "my_default_func"
	        ],
	        "type":[
	            "0",
	            "my_default_func"
	        ],
	        "product_name":[
	            "new['simple_name']",
	            "my_eval_func"
	        ],
	        "photo_urls":[
	            "[new['product_url']]",
	            "my_eval_func"
	        ]
	    },
	    "trans_corp_map":{
	        "simple_name":[
	            "new['company_name']",
	            "my_eval_func"
	        ],
	        "business":[
	            "new['key_words']",
	            "my_eval_func"
	        ],
	        "client_time":[
	            "",
	            "my_milltime_func"
	        ],
	        "company_web":[
	            "[new['company_web']]",
	            "my_eval_func"
	        ],
	        "logo_url":[
	            "new['logo_url']",
	            "my_eval_func"
	        ],
	        "opponents":[
	            "new['rival_companies']",
	            "my_eval_func"
	        ],
	        "description":[
	            "new['description']",
	            "my_eval_func"
	        ],
	        "key_words":[
	            "new['key_words']",
	            "my_eval_func"
	        ],
	        "style":[
	            "1",
	            "my_default_func"
	        ],
	        "source":[
	            "11",
	            "my_default_func"
	        ]
	    }
	}
}